# Generated by Django 6.0.4 on 2026-04-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=10)),
                ("instituicao", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("duracao_anos", models.IntegerField()),
                ("total_ects", models.IntegerField()),
                ("link_oficial", models.URLField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="licenciaturas/")),
            ],
        ),
    ]
