# Generated by Django 6.0.4 on 2026-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("link_pagina_pessoal", models.URLField(blank=True)),
                ("foto", models.ImageField(blank=True, upload_to="docentes/")),
                (
                    "habilitacao",
                    models.CharField(
                        choices=[
                            ("ALU_MES", "Aluno de Mestrado"),
                            ("MES", "Mestrado"),
                            ("ALU_DOUT", "Aluno de Doutoramento"),
                            ("DOUT", "Doutoramento"),
                            ("AGR", "Agregação"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "regime_contrato",
                    models.CharField(
                        choices=[("TI", "Tempo Integral"), ("TP", "Tempo Parcial")],
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
