# Generated by Django 6.0.4 on 2026-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=20)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="ucs/")),
                ("link_pagina", models.URLField(blank=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
