# Generated by Django 6.0.4 on 2026-04-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEC", "Técnica"),
                            ("SOFT", "Soft Skill"),
                            ("LING", "Linguística"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("BAS", "Básico"),
                            ("INT", "Intermédio"),
                            ("AVA", "Avançado"),
                        ],
                        max_length=5,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
    ]
