# Generated by Django 6.0.4 on 2026-04-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("LING", "Linguagem"),
                            ("FRAME", "Framework"),
                            ("FERR", "Ferramenta"),
                            ("BD", "Base de Dados"),
                        ],
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("link_oficial", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Muito Baixo"),
                            (2, "2 - Baixo"),
                            (3, "3 - Médio"),
                            (4, "4 - Alto"),
                            (5, "5 - Muito Alto"),
                        ],
                        default=3,
                    ),
                ),
                ("aspetos_relevantes", models.TextField(blank=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tecnologias",
                        to="portfolio.competencia",
                    ),
                ),
            ],
        ),
    ]
