# Generated by Django 6.0.4 on 2026-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("sumario", models.TextField()),
                ("autores", models.CharField(blank=True, max_length=500)),
                ("orientadores", models.CharField(blank=True, max_length=500)),
                ("imagem", models.URLField(blank=True)),
                ("link_pdf", models.URLField(blank=True)),
                ("palavras_chave", models.CharField(blank=True, max_length=500)),
                ("areas", models.CharField(blank=True, max_length=500)),
                ("tecnologias_usadas", models.CharField(blank=True, max_length=500)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Muito Baixo"),
                            (2, "2 - Baixo"),
                            (3, "3 - Médio"),
                            (4, "4 - Alto"),
                            (5, "5 - Muito Alto"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.licenciatura"
                    ),
                ),
            ],
        ),
    ]
