# Generated by Django 6.0.4 on 2026-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("certificado", models.FileField(blank=True, upload_to="formacoes/")),
                ("link", models.URLField(blank=True)),
            ],
        ),
    ]
