# Generated by Django 6.0.4 on 2026-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateField()),
                ("descricao_processo", models.TextField()),
                ("decisoes_tomadas", models.TextField(blank=True)),
                ("erros_e_correcoes", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("foto_caderno", models.ImageField(blank=True, upload_to="makingof/")),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="makingofs", to="portfolio.competencia"
                    ),
                ),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="makingofs", to="portfolio.docente"
                    ),
                ),
                (
                    "formacoes",
                    models.ManyToManyField(
                        blank=True, related_name="makingofs", to="portfolio.formacao"
                    ),
                ),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="makingofs",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="makingofs", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="makingofs", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "tfcs",
                    models.ManyToManyField(
                        blank=True, related_name="makingofs", to="portfolio.tfc"
                    ),
                ),
                (
                    "ucs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="makingofs",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
